spring:
  application:
    name: restaurants-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss"
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
    register-with-eureka: true
    fetch-registry: true
aws:
  s3:
    bucket: ${AWS_S3_BUCKET}   # S3 버킷 이름
    region: ${AWS_REGION}      # ap-northeast-2 (서울 리전 등)
    access-key: ${AWS_ACCESS_KEY_ID}   # IAM 사용자 키
    secret-key: ${AWS_SECRET_ACCESS_KEY}